## *********************************************************
##
## File autogenerated for the depthai_filters package
## by the dynamic_reconfigure package.
## Please do not edit.
##
## ********************************************************/

from dynamic_reconfigure.encoding import extract_params

inf = float('inf')

config_description = {'name': 'Default', 'type': '', 'state': True, 'cstate': 'true', 'id': 0, 'parent': 0, 'parameters': [], 'groups': [{'name': 'wls', 'type': '', 'state': True, 'cstate': 'true', 'id': 1, 'parent': 0, 'parameters': [{'name': 'lambda', 'type': 'int', 'default': 8000, 'level': 0, 'description': 'WLS Lambda', 'min': 0, 'max': 20000, 'srcline': 11, 'srcfile': '/home/tony/catkin_ws/src/depthai-ros/depthai_filters/cfg/wls.cfg', 'edit_method': '', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'sigma', 'type': 'double', 'default': 1.5, 'level': 0, 'description': 'WLS Sigma', 'min': 0.0, 'max': 2.0, 'srcline': 12, 'srcfile': '/home/tony/catkin_ws/src/depthai-ros/depthai_filters/cfg/wls.cfg', 'edit_method': '', 'ctype': 'double', 'cconsttype': 'const double'}], 'groups': [], 'srcline': 124, 'srcfile': '/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py', 'class': 'DEFAULT::WLS', 'parentclass': 'DEFAULT', 'parentname': 'Default', 'field': 'DEFAULT::wls', 'upper': 'WLS', 'lower': 'wls'}], 'srcline': 246, 'srcfile': '/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py', 'class': 'DEFAULT', 'parentclass': '', 'parentname': 'Default', 'field': 'default', 'upper': 'DEFAULT', 'lower': 'groups'}

min = {}
max = {}
defaults = {}
level = {}
type = {}
all_level = 0

#def extract_params(config):
#    params = []
#    params.extend(config['parameters'])
#    for group in config['groups']:
#        params.extend(extract_params(group))
#    return params

for param in extract_params(config_description):
    min[param['name']] = param['min']
    max[param['name']] = param['max']
    defaults[param['name']] = param['default']
    level[param['name']] = param['level']
    type[param['name']] = param['type']
    all_level = all_level | param['level']

