(cl:defpackage depthai_ros_msgs-msg
  (:use )
  (:export
   "<AUTOFOCUSCTRL>"
   "AUTOFOCUSCTRL"
   "<HANDLANDMARK>"
   "HANDLANDMARK"
   "<HANDLANDMARKARRAY>"
   "HANDLANDMARKARRAY"
   "<IMAGEMARKER>"
   "IMAGEMARKER"
   "<IMAGEMARKERARRAY>"
   "IMAGEMARKERARRAY"
   "<IMUWITHMAGNETICFIELD>"
   "IMUWITHMAGNETICFIELD"
   "<SPATIALDETECTION>"
   "SPATIALDETECTION"
   "<SPATIALDETECTIONARRAY>"
   "SPATIALDETECTIONARRAY"
   "<TRACKEDFEATURE>"
   "TRACKEDFEATURE"
   "<TRACKEDFEATURES>"
   "TRACKEDFEATURES"
  ))

